{% set name = "pattern" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Pattern/Pattern-{{ version }}.tar.gz
  sha256: 1ced3336a5189e3025ece970229126bc7e6adf2e73a91c2e625b3a45eb0720d9

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python

  run:
    - libsvm
    - backports.csv
    - beautifulsoup4
    - cherrypy
    - feedparser
    - future
    - lxml
    - mysqlclient
    - nltk
    - numpy
    - pdfminer.six
    - python
    - python-docx
    - requests
    - scipy

test:
  imports:
    - pattern
    - pattern.db
    - pattern.graph
    - pattern.text
    - pattern.text.de
    - pattern.text.en
    - pattern.text.en.wordlist
    - pattern.text.en.wordnet
    - pattern.text.es
    - pattern.text.fr
    - pattern.text.it
    - pattern.text.nl
    - pattern.text.ru
    - pattern.text.ru.wordlist
    - pattern.vector
    - pattern.web
    - pattern.web.cache
    - pattern.web.imap
    - pattern.web.locale
    - pattern.web.oauth

about:
  home: https://github.com/clips/pattern
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Web mining module for Python, with tools for scraping, natural language processing, machine learning, network analysis and visualization.'
  dev_url: https://github.com/clips/pattern
  doc_url: https://github.com/clips/pattern/wiki

extra:
  recipe-maintainers:
    - benhuff
    - rluria14
    - oblute
